-- ============================================================
-- Seed data uji performa: 100.000 data
-- ============================================================

-- 10.000 pasien tambahan
INSERT INTO pasien (no_rm, nik, nama, jenis_kelamin, tempat_lahir, tanggal_lahir, golongan_darah, alamat, telepon, pekerjaan, penjamin)
SELECT 
    CONCAT('RM-', LPAD(n.n + 100, 6, '0')),
    CONCAT('32', LPAD(n.n + 100000000, 14, '0')),
    CONCAT('Pasien Uji ', n.n),
    IF(n.n % 2 = 0, 'L', 'P'),
    'Jakarta',
    DATE_SUB(CURDATE(), INTERVAL (n.n % 36500) DAY),
    ELT(FLOOR(1 + RAND() * 4), 'A', 'B', 'AB', 'O'),
    CONCAT('Jl. Uji No. ', n.n),
    CONCAT('08', LPAD(n.n, 10, '0')),
    ELT(FLOOR(1 + RAND() * 4), 'Karyawan', 'Wiraswasta', 'Mahasiswa', 'Pelajar'),
    ELT(FLOOR(1 + RAND() * 3), 'Umum', 'BPJS', 'Asuransi')
FROM (
    SELECT @rownum := @rownum + 1 AS n
    FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t3,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t4,
         (SELECT @rownum := 0) r
    LIMIT 10000
) n;

-- 100 dokter tambahan
INSERT INTO dokter (nip, nama, spesialisasi, poli_id, telepon, jadwal, aktif)
SELECT 
    CONCAT('NIP', LPAD(n.n + 1000, 10, '0')),
    CONCAT('dr. Dokter Uji ', n.n, IF(n.n % 3 = 0, ', Sp.A', IF(n.n % 3 = 1, ', Sp.PD', ''))),
    ELT(FLOOR(1 + RAND() * 5), 'Dokter Umum', 'Spesialis Anak', 'Spesialis Penyakit Dalam', 'Spesialis Kandungan', 'Dokter Gigi'),
    1 + (n.n % 6),
    CONCAT('081', LPAD(n.n, 8, '0')),
    'Senin-Jumat 08:00-14:00',
    1
FROM (
    SELECT @rownum := @rownum + 1 AS n
    FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2,
         (SELECT @rownum := 0) r
    LIMIT 100
) n;

-- 500 obat tambahan
INSERT INTO obat (kode, nama, satuan, stok, harga, kadaluarsa)
SELECT 
    CONCAT('OBT-', LPAD(n.n + 100, 5, '0')),
    CONCAT('Obat Uji ', n.n, ' ', ELT(FLOOR(1 + RAND() * 5), '500mg', '250mg', '100mg', '10ml', '50g')),
    ELT(FLOOR(1 + RAND() * 5), 'tablet', 'kapsul', 'botol', 'tube', 'ampul'),
    FLOOR(100 + RAND() * 1000),
    FLOOR(1000 + RAND() * 100000),
    DATE_ADD(CURDATE(), INTERVAL (n.n % 1095) DAY)
FROM (
    SELECT @rownum := @rownum + 1 AS n
    FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t3,
         (SELECT @rownum := 0) r
    LIMIT 500
) n;

-- 50.000 pendaftaran
INSERT INTO pendaftaran (no_registrasi, no_antrian, pasien_id, poli_id, dokter_id, tanggal, keluhan, status, dipanggil_pada)
SELECT 
    CONCAT('REG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL (n.n % 365) DAY), '%Y%m%d'), '-', LPAD(n.n % 10000, 4, '0')),
    CONCAT(ELT(FLOOR(1 + RAND() * 6), 'UMU', 'GIG', 'ANA', 'KAN', 'DAL', 'MAT'), '-', LPAD(n.n % 999 + 1, 3, '0')),
    FLOOR(1 + RAND() * 10000),
    FLOOR(1 + RAND() * 6),
    FLOOR(1 + RAND() * 100),
    DATE_SUB(CURDATE(), INTERVAL (n.n % 365) DAY),
    CONCAT('Keluhan uji ', n.n, ': ', ELT(FLOOR(1 + RAND() * 5), 'Demam', 'Batuk', 'Pusing', 'Mual', 'Nyeri')),
    ELT(FLOOR(1 + RAND() * 5), 'menunggu', 'dipanggil', 'diperiksa', 'selesai', 'batal'),
    IF(RAND() > 0.5, DATE_SUB(CURDATE(), INTERVAL (n.n % 365) DAY), NULL)
FROM (
    SELECT @rownum := @rownum + 1 AS n
    FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t3,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t4,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t5,
         (SELECT @rownum := 0) r
    LIMIT 50000
) n;

-- 20.000 rekam medis
INSERT INTO rekam_medis (pendaftaran_id, pasien_id, dokter_id, tanggal, anamnesa, tekanan_darah, suhu, berat_badan, tinggi_badan, pemeriksaan_fisik, diagnosis, tindakan, biaya_tindakan, catatan)
SELECT 
    n.n,
    FLOOR(1 + RAND() * 10000),
    FLOOR(1 + RAND() * 100),
    DATE_SUB(CURDATE(), INTERVAL (n.n % 365) DAY),
    CONCAT('Anamnesa uji ', n.n),
    CONCAT(FLOOR(100 + RAND() * 60), '/', FLOOR(60 + RAND() * 40)),
    ROUND(36 + RAND() * 3, 1),
    ROUND(50 + RAND() * 50, 1),
    ROUND(150 + RAND() * 50, 1),
    CONCAT('Pemeriksaan fisik uji ', n.n),
    CONCAT('Diagnosis uji ', n.n, ': ', ELT(FLOOR(1 + RAND() * 5), 'Hipertensi', 'Diabetes', 'Gastritis', 'ISPA', 'Migren')),
    CONCAT('Tindakan uji ', n.n),
    FLOOR(10000 + RAND() * 500000),
    CONCAT('Catatan uji ', n.n)
FROM (
    SELECT @rownum := @rownum + 1 AS n
    FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t3,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t4,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t5,
         (SELECT @rownum := 0) r
    LIMIT 20000
) n;

-- 30.000 resep
INSERT INTO resep (rekam_medis_id, obat_id, jumlah, aturan_pakai)
SELECT 
    FLOOR(1 + RAND() * 20000),
    FLOOR(1 + RAND() * 500),
    FLOOR(1 + RAND() * 30),
    ELT(FLOOR(1 + RAND() * 4), '1x1 sehari', '2x1 sehari', '3x1 sehari', '4x1 sehari')
FROM (
    SELECT @rownum := @rownum + 1 AS n
    FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t3,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t4,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t5,
         (SELECT @rownum := 0) r
    LIMIT 30000
) n;

-- 15.000 tagihan
INSERT INTO tagihan (no_invoice, pendaftaran_id, tanggal, biaya_konsultasi, biaya_tindakan, biaya_obat, total, metode_pembayaran, status, dibayar_pada)
SELECT 
    CONCAT('INV-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL (n.n % 365) DAY), '%Y%m%d'), '-', LPAD(n.n % 10000, 4, '0')),
    n.n,
    DATE_SUB(CURDATE(), INTERVAL (n.n % 365) DAY),
    FLOOR(25000 + RAND() * 100000),
    FLOOR(10000 + RAND() * 500000),
    FLOOR(5000 + RAND() * 200000),
    FLOOR(25000 + RAND() * 100000) + FLOOR(10000 + RAND() * 500000) + FLOOR(5000 + RAND() * 200000),
    ELT(FLOOR(1 + RAND() * 4), 'Tunai', 'Transfer', 'BPJS', 'Asuransi'),
    ELT(FLOOR(1 + RAND() * 2), 'belum', 'lunas'),
    IF(RAND() > 0.5, DATE_SUB(CURDATE(), INTERVAL (n.n % 365) DAY), NULL)
FROM (
    SELECT @rownum := @rownum + 1 AS n
    FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t3,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t4,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t5,
         (SELECT @rownum := 0) r
    LIMIT 15000
) n;

-- 5.000 mutasi stok
INSERT INTO mutasi_stok (obat_id, tipe, jumlah, keterangan, referensi, user_id)
SELECT 
    FLOOR(1 + RAND() * 500),
    ELT(FLOOR(1 + RAND() * 2), 'masuk', 'keluar'),
    FLOOR(1 + RAND() * 100),
    CONCAT('Mutasi uji ', n.n),
    CONCAT('REF-', LPAD(n.n, 6, '0')),
    FLOOR(1 + RAND() * 3)
FROM (
    SELECT @rownum := @rownum + 1 AS n
    FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t3,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t4,
         (SELECT @rownum := 0) r
    LIMIT 5000
) n;

-- 3.000 janji temu
INSERT INTO janji_temu (pasien_id, poli_id, dokter_id, tanggal, jam, keluhan, status, pendaftaran_id)
SELECT 
    FLOOR(1 + RAND() * 10000),
    FLOOR(1 + RAND() * 6),
    FLOOR(1 + RAND() * 100),
    DATE_ADD(CURDATE(), INTERVAL (n.n % 90) DAY),
    SEC_TO_TIME(FLOOR(28800 + RAND() * 25200)),
    CONCAT('Janji temu uji ', n.n),
    ELT(FLOOR(1 + RAND() * 3), 'dijadwalkan', 'hadir', 'batal'),
    IF(RAND() > 0.5, FLOOR(1 + RAND() * 50000), NULL)
FROM (
    SELECT @rownum := @rownum + 1 AS n
    FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t3,
         (SELECT @rownum := 0) r
    LIMIT 3000
) n;

-- 2.000 surat keterangan
INSERT INTO surat_keterangan (no_surat, rekam_medis_id, jenis, isi)
SELECT 
    CONCAT('SK-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL (n.n % 365) DAY), '%Y%m%d'), '-', LPAD(n.n % 1000, 3, '0')),
    FLOOR(1 + RAND() * 20000),
    ELT(FLOOR(1 + RAND() * 2), 'sakit', 'rujukan'),
    CONCAT('Surat keterangan uji ', n.n, ' untuk keperluan administrasi.')
FROM (
    SELECT @rownum := @rownum + 1 AS n
    FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t3,
         (SELECT @rownum := 0) r
    LIMIT 2000
) n;
